# docker-compose.yml
services:
  obol:
    build: .
    restart: unless-stopped
    ports:
      - "3090:3090" # Host port : Container port
    env_file: .env
    volumes:
      - ./data:/usr/src/app/data